This noteebook it's to create some csv from external data

In [1]:
import pandas as pd 

from io import StringIO

In [3]:
data='date,UNRATE\n2000-01-01,4.0\n2000-02-01,4.1\n2000-03-01,4.0\n2000-04-01,3.8\n2000-05-01,4.0\n2000-06-01,4.0\n2000-07-01,4.0\n2000-08-01,4.1\n2000-09-01,3.9\n2000-10-01,3.9\n2000-11-01,3.9\n2000-12-01,3.9\n2001-01-01,4.2\n2001-02-01,4.2\n2001-03-01,4.3\n2001-04-01,4.4\n2001-05-01,4.3\n2001-06-01,4.5\n2001-07-01,4.6\n2001-08-01,4.9\n2001-09-01,5.0\n2001-10-01,5.3\n2001-11-01,5.5\n2001-12-01,5.7\n2002-01-01,5.7\n2002-02-01,5.7\n2002-03-01,5.7\n2002-04-01,5.9\n2002-05-01,5.8\n2002-06-01,5.8\n2002-07-01,5.8\n2002-08-01,5.7\n2002-09-01,5.7\n2002-10-01,5.7\n2002-11-01,5.9\n2002-12-01,6.0\n2003-01-01,5.8\n2003-02-01,5.9\n2003-03-01,5.9\n2003-04-01,6.0\n2003-05-01,6.1\n2003-06-01,6.3\n2003-07-01,6.2\n2003-08-01,6.1\n2003-09-01,6.1\n2003-10-01,6.0\n2003-11-01,5.8\n2003-12-01,5.7\n2004-01-01,5.7\n2004-02-01,5.6\n2004-03-01,5.8\n2004-04-01,5.6\n2004-05-01,5.6\n2004-06-01,5.6\n2004-07-01,5.5\n2004-08-01,5.4\n2004-09-01,5.4\n2004-10-01,5.5\n2004-11-01,5.4\n2004-12-01,5.4\n2005-01-01,5.3\n2005-02-01,5.4\n2005-03-01,5.2\n2005-04-01,5.2\n2005-05-01,5.1\n2005-06-01,5.0\n2005-07-01,5.0\n2005-08-01,4.9\n2005-09-01,5.0\n2005-10-01,5.0\n2005-11-01,5.0\n2005-12-01,4.9\n2006-01-01,4.7\n2006-02-01,4.8\n2006-03-01,4.7\n2006-04-01,4.7\n2006-05-01,4.6\n2006-06-01,4.6\n2006-07-01,4.7\n2006-08-01,4.7\n2006-09-01,4.5\n2006-10-01,4.4\n2006-11-01,4.5\n2006-12-01,4.4\n2007-01-01,4.6\n2007-02-01,4.5\n2007-03-01,4.4\n2007-04-01,4.5\n2007-05-01,4.4\n2007-06-01,4.6\n2007-07-01,4.7\n2007-08-01,4.6\n2007-09-01,4.7\n2007-10-01,4.7\n2007-11-01,4.7\n2007-12-01,5.0\n2008-01-01,5.0\n2008-02-01,4.9\n2008-03-01,5.1\n2008-04-01,5.0\n2008-05-01,5.4\n2008-06-01,5.6\n2008-07-01,5.8\n2008-08-01,6.1\n2008-09-01,6.1\n2008-10-01,6.5\n2008-11-01,6.8\n2008-12-01,7.3\n2009-01-01,7.8\n2009-02-01,8.3\n2009-03-01,8.7\n2009-04-01,9.0\n2009-05-01,9.4\n2009-06-01,9.5\n2009-07-01,9.5\n2009-08-01,9.6\n2009-09-01,9.8\n2009-10-01,10.0\n2009-11-01,9.9\n2009-12-01,9.9\n2010-01-01,9.8\n2010-02-01,9.8\n2010-03-01,9.9\n2010-04-01,9.9\n2010-05-01,9.6\n2010-06-01,9.4\n2010-07-01,9.4\n2010-08-01,9.5\n2010-09-01,9.5\n2010-10-01,9.4\n2010-11-01,9.8\n2010-12-01,9.3\n2011-01-01,9.1\n2011-02-01,9.0\n2011-03-01,9.0\n2011-04-01,9.1\n2011-05-01,9.0\n2011-06-01,9.1\n2011-07-01,9.0\n2011-08-01,9.0\n2011-09-01,9.0\n2011-10-01,8.8\n2011-11-01,8.6\n2011-12-01,8.5\n2012-01-01,8.3\n2012-02-01,8.3\n2012-03-01,8.2\n2012-04-01,8.2\n2012-05-01,8.2\n2012-06-01,8.2\n2012-07-01,8.2\n2012-08-01,8.1\n2012-09-01,7.8\n2012-10-01,7.8\n2012-11-01,7.7\n2012-12-01,7.9\n2013-01-01,8.0\n2013-02-01,7.7\n2013-03-01,7.5\n2013-04-01,7.6\n2013-05-01,7.5\n2013-06-01,7.5\n2013-07-01,7.3\n2013-08-01,7.3\n2013-09-01,7.2\n2013-10-01,7.2\n2013-11-01,6.9\n2013-12-01,6.7\n2014-01-01,6.6\n2014-02-01,6.7\n2014-03-01,6.7\n2014-04-01,6.2\n2014-05-01,6.3\n2014-06-01,6.1\n2014-07-01,6.2\n2014-08-01,6.2\n2014-09-01,5.9\n2014-10-01,5.7\n2014-11-01,5.8\n2014-12-01,5.6\n2015-01-01,5.7\n2015-02-01,5.5\n2015-03-01,5.4\n2015-04-01,5.4\n2015-05-01,5.5\n2015-06-01,5.3\n2015-07-01,5.2\n2015-08-01,5.1\n2015-09-01,5.0\n2015-10-01,5.0\n2015-11-01,5.0\n2015-12-01,5.0\n2016-01-01,4.9\n2016-02-01,4.9\n2016-03-01,5.0\n2016-04-01,5.0\n2016-05-01,4.7\n2016-06-01,4.9\n2016-07-01,4.9\n2016-08-01,4.9\n2016-09-01,4.9\n2016-10-01,4.8\n2016-11-01,4.6\n2016-12-01,4.7\n2017-01-01,4.8\n2017-02-01,4.7\n2017-03-01,4.5\n2017-04-01,4.4\n2017-05-01,4.3\n'

In [4]:
unemployment = pd.read_csv(StringIO(data),sep=",") 

print(unemployment.head())

         date  UNRATE
0  2000-01-01     4.0
1  2000-02-01     4.1
2  2000-03-01     4.0
3  2000-04-01     3.8
4  2000-05-01     4.0

In [5]:
unemployment.to_csv("datasets/Stock_data-/unemployment.csv")